CREATE TABLE Contact(
	ID_Contact SERIAL PRIMARY KEY,
	ID_ContactType INT REFERENCES ContactType(ID_ContactType) NOT NULL,
	Name VARCHAR(30) NOT NULL,
	Last_Name VARCHAR(30) NOT NULL,
	Date_register TIMESTAMP NOT NULL DEFAULT NOW(),
	Phone CHAR(10) NULL,
	Email VARCHAR(50) NOT NULL UNIQUE,
	Password BYTEA NOT NULL
)