CREATE TABLE Reservation(
	ID_Reservation SERIAL PRIMARY KEY,
	ID_Contact INT REFERENCES Contact(ID_Contact) NOT NULL,
	Start_Date DATE DEFAULT CURRENT_DATE NOT NULL,
	End_Date DATE NOT NULL,
	Date_Register TIMESTAMP DEFAULT NOW() NOT NULL
)